import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
 import nookies,{parseCookies} from "nookies"
import netList from 'network-list';
import { useEffect, useState } from 'react';

export default function Home() {
  const cookies = parseCookies()
  
  const [state,setState] = useState([])
 

  useEffect(() => {
    const { fromGetInitialProps } = cookies
    setState(JSON.parse(fromGetInitialProps || []))
  },[setState])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       {
         state.length && (
          <div>
            { state[0].ip }
          </div>
         )
       }
    </div>
  )
}

const list = (n) => new Promise((resolve) => {
  const items = []
  n.scanEach({}, (err, obj) => {
    if(obj.alive) {
     
      items.push(obj)
      resolve(items)
    }
  });
 
})

export async function getServerSideProps(context) {
  const cookies = nookies.get(context)
  
  const res = await list(netList)
 
 
    nookies.set(context, 'fromGetInitialProps', JSON.stringify(res), {
      maxAge: 30 * 24 * 60 * 60,
    })
 
  
  // netList.scan({}, (err, arr) => {
  //     // console.log(arr); // array with all devices
  // });
 

  return {
    props: {}, // will be passed to the page component as props
  }
}
